### PR TITLE
Add zsh-style plugin for easy load

### PR DESCRIPTION
**Pull request by akatrevorjay**

### CODE REVIEW

**Comment by erichs** [comment]
Hi! Is this intended for integration with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)? How would this `.zsh` file be used?

**Comment by akatrevorjay** [comment]
It's for any ZSH plugin supporting system. You just include `erichs/composure' in the plugin list, and it will download the repo and execute this script.

**Comment by akatrevorjay** [comment]
Example: https://github.com/akatrevorjay/dotfiles/blob/develop/.zsh/zshplugins#L16

**Comment by erichs** [comment]
Cool, thanks!

**Pull request merged**
